---
- set_fact: 
    tmp_path: /tmp/db_setup_install/db_create

- name: Create temp directory to store all execution data
  file: 
    path: "{{ tmp_path }}"
    state: directory
    recurse: yes
    owner: oracle
    group: dba
    mode: ug+rwx,o+rx,g+s

- name: copy the template to /tmp for db version {{ ORACLE_VER }}
  template: 
    src: "dbca_{{ ORACLE_VER }}.rsp"
    dest: "{{ tmp_path }}"
    backup: yes
    mode: 0644
    owner: oracle
    group: dba

- name: "copy run template to {{ tmp_path }} for db version {{ ORACLE_VER }}"
  template: 
    src: create_dbca.sh
    dest: "{{ tmp_path }}"
    backup: yes
    mode: 0644
    owner: oracle
    group: dba
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int >= 7

- name: "copy run template to {{ tmp_path }} for db version {{ ORACLE_VER }}"
  template: 
    src: create_dbca_v6.sh
    dest: "{{ tmp_path }}"
    backup: yes
    mode: 0644
    owner: oracle
    group: dba
  when: hostvars[inventory_hostname].ansible_distribution_major_version|int <= 6

- name: create the database with version {{ ORACLE_VER }}
  command: sh /{{ tmp_path }}/create_dbca.sh
